apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resources-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
      - name: app
        image: operationcode/resources-api:latest
        command: ["flask"]
        args: ["run", "-h", "0.0.0.0"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: resources-api-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: resources-api-secrets
              key: postgres_password
        - name: ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: resources-api-secrets
              key: algolia_app_id
        - name: ALGOLIA_API_KEY
          valueFrom:
            secretKeyRef:
              name: resources-api-secrets
              key: algolia_api_key
        - name: INDEX_NAME
          value: resources_api
        - name: POSTGRES_DB
          value: resources_api
        - name: POSTGRES_HOST
          value: resources-postgres
        - name: HONEYCOMB_WRITEKEY
          valueFrom:
            secretKeyRef:
              name: python-backend-secrets
              key: honeycomb_writekey
        - name: HONEYCOMB_DATASET
          value: production-traces
      volumes:
      - name: resources-api-secrets
        secret:
          secretName: resources-api-secrets
