
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-api
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: FLASK_ENV
          value: staging
        - name: HONEYCOMB_DATASET
          value: staging-traces
