---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: operationcode-backend
  region: us-east-2

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: operationcode-backends
    selectors:
      - namespace: operationcode
      - namespace: operationcode-staging

nodeGroups:
  - name: eks-infra-spot
    minSize: 3
    desiredCapacity: 3
    maxSize: 5
    # use Spot instance pricing
    instancesDistribution:
      instanceTypes:
      - t3.small
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: oc-ops
    labels:
      nodegroup-type: infra
    tags:
      Name: eks-infra-spot
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
